using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.Data.Sqlite;

namespace Sqlite2MySql;

internal static class Converter
{
    private static readonly Regex DecimalPattern = new(@"DECIMAL\s*\(\s*\d+\s*,\s*\d+\s*\)", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex VarcharPattern = new(@"(VAR)?CHAR\s*\(\s*\d+\s*\)", RegexOptions.IgnoreCase | RegexOptions.Compiled);

    public static ConversionResult ConvertDatabase(ConvertOptions options)
    {
        if (options.BatchSize <= 0)
        {
            throw new InvalidOperationException("Batch size must be positive.");
        }

        var connectionString = new SqliteConnectionStringBuilder
        {
            DataSource = options.SQLitePath,
            Mode = SqliteOpenMode.ReadOnly
        }.ToString();

        using var connection = new SqliteConnection(connectionString);
        connection.Open();

        var tables = new List<(string Name, string Sql)>();
        using (var tableCmd = connection.CreateCommand())
        {
            tableCmd.CommandText = "SELECT name, sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name";
            using var tableReader = tableCmd.ExecuteReader();
            while (tableReader.Read())
            {
                tables.Add((
                    tableReader.GetString(0),
                    tableReader.IsDBNull(1) ? string.Empty : tableReader.GetString(1)
                ));
            }
        }

        using var writer = CreateWriter(options.OutputPath);
        WriteHeader(writer, options.SQLitePath, options.Database);

        long totalRows = 0;
        for (var i = 0; i < tables.Count; i++)
        {
            var (tableName, tableSql) = tables[i];
            options.Progress?.Report(new ConversionProgress
            {
                CurrentTable = i + 1,
                TotalTables = tables.Count,
                TableName = tableName
            });

            writer.WriteLine($"DROP TABLE IF EXISTS {QuoteIdentifier(tableName)};");

            var (createSql, nullablePk, nullablePkValueKind) = BuildCreateTableStatement(connection, tableName, tableSql);
            writer.WriteLine(createSql);

            if (options.IncludeData)
            {
                totalRows += DumpTableData(connection, tableName, options.BatchSize, nullablePk, nullablePkValueKind, writer);
            }

            foreach (var stmt in DumpTableIndexes(connection, tableName))
            {
                writer.WriteLine(stmt);
            }

            writer.WriteLine();
        }

        DumpViews(connection, writer);
        DumpTriggers(connection, writer);

        writer.WriteLine("SET FOREIGN_KEY_CHECKS=1;");
        writer.Flush();

        return new ConversionResult { TablesCount = tables.Count, RowsCount = totalRows };
    }

    private static TextWriter CreateWriter(string? outputPath)
    {
        if (string.IsNullOrWhiteSpace(outputPath))
        {
            return Console.Out;
        }

        var stream = new FileStream(outputPath, FileMode.Create, FileAccess.Write, FileShare.Read);
        return new StreamWriter(stream, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    }

    private static void WriteHeader(TextWriter writer, string sqlitePath, string? database)
    {
        writer.WriteLine($"-- Generated by sqlite2mysql (V0.1 .NET) from {sqlitePath}");
        writer.WriteLine("SET NAMES utf8mb4;");
        writer.WriteLine("SET sql_mode=ANSI_QUOTES;");
        writer.WriteLine("SET FOREIGN_KEY_CHECKS=0;");
        writer.WriteLine();

        if (!string.IsNullOrWhiteSpace(database))
        {
            writer.WriteLine($"CREATE DATABASE IF NOT EXISTS {QuoteIdentifier(database)} DEFAULT CHARACTER SET utf8mb4;");
            writer.WriteLine($"USE {QuoteIdentifier(database)};");
            writer.WriteLine();
        }
    }

    private static string QuoteIdentifier(string value)
        => $"`{value.Replace("`", "``")}`";

    private static (string createSql, HashSet<string> nullablePk, IReadOnlyDictionary<string, string> nullablePkValueKind) BuildCreateTableStatement(SqliteConnection connection, string tableName, string tableSql)
    {
        var columns = new List<TableInfo>();
        using (var cmd = connection.CreateCommand())
        {
            cmd.CommandText = $"PRAGMA table_info({QuoteIdentifier(tableName)})";
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                columns.Add(new TableInfo
                {
                    Name = reader.GetString(1),
                    Type = reader.IsDBNull(2) ? null : reader.GetString(2),
                    NotNull = reader.GetInt32(3) != 0,
                    DefaultValue = reader.IsDBNull(4) ? null : reader.GetString(4),
                    PkSeq = reader.GetInt32(5)
                });
            }
        }

        var indexedCols = IndexedColumns(connection, tableName);
        var pkColumns = new List<string>();
        var nullablePk = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var nullablePkValueKind = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        var columnLines = new List<string>();
        var hasAutoincrement = tableSql.Contains("AUTOINCREMENT", StringComparison.OrdinalIgnoreCase);

        foreach (var col in columns)
        {
            var mysqlType = MapSQLiteType(col.Type);

            if (mysqlType == "TEXT")
            {
                if (IsDatetimeDefault(col.DefaultValue))
                {
                    mysqlType = "DATETIME";
                }
                else if (IsDateDefault(col.DefaultValue))
                {
                    mysqlType = "DATE";
                }
                else if (IsTimeDefault(col.DefaultValue))
                {
                    mysqlType = "TIME";
                }
                else if (!string.IsNullOrWhiteSpace(col.DefaultValue))
                {
                    mysqlType = "VARCHAR(255)";
                }
            }

            if (mysqlType == "TEXT" && (col.PkSeq > 0 || indexedCols.Contains(col.Name)))
            {
                mysqlType = "VARCHAR(191)";
            }
            if (mysqlType == "BLOB" && (col.PkSeq > 0 || indexedCols.Contains(col.Name)))
            {
                mysqlType = "VARBINARY(191)";
            }
            if (mysqlType == "BLOB" && !string.IsNullOrWhiteSpace(col.DefaultValue))
            {
                mysqlType = "VARBINARY(255)";
            }

            var line = new StringBuilder();
            line.Append(QuoteIdentifier(col.Name)).Append(' ').Append(mysqlType);

            if (col.PkSeq > 0)
            {
                pkColumns.Add(col.Name);
                if (!col.NotNull)
                {
                    nullablePk.Add(col.Name);
                    nullablePkValueKind[col.Name] = ValueKindForType(mysqlType);
                }
            }

            line.Append(col.NotNull || col.PkSeq > 0 ? " NOT NULL" : " NULL");

            if (!string.IsNullOrWhiteSpace(col.DefaultValue))
            {
                line.Append(" DEFAULT ").Append(FormatDefaultValue(col.DefaultValue));
            }

            if (hasAutoincrement && pkColumns.Count == 1 && pkColumns[0] == col.Name && IsIntegerType(col.Type))
            {
                line.Append(" AUTO_INCREMENT");
            }

            columnLines.Add(line.ToString());
        }

        if (pkColumns.Count > 0)
        {
            var pk = string.Join(", ", pkColumns.Select(QuoteIdentifier));
            columnLines.Add($"PRIMARY KEY ({pk})");
        }

        var joined = string.Join(",\n  ", columnLines);
        var createSql = $"CREATE TABLE {QuoteIdentifier(tableName)} (\n  {joined}\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;";
        return (createSql, nullablePk, nullablePkValueKind);
    }

    private static string ValueKindForType(string mysqlType)
    {
        if (string.IsNullOrWhiteSpace(mysqlType)) return "text";
        var t = mysqlType.Trim().ToUpperInvariant();
        if (t.StartsWith("TINYINT") || t.StartsWith("SMALLINT") || t.StartsWith("BIGINT") || t.StartsWith("INT")) return "int";
        if (t.StartsWith("REAL") || t.StartsWith("DOUBLE") || t.StartsWith("FLOAT") || t.StartsWith("DECIMAL")) return "real";
        if (t.StartsWith("BLOB") || t.StartsWith("VARBINARY") || t.StartsWith("BINARY")) return "blob";
        return "text";
    }

    private static string MapSQLiteType(string? rawType)
    {
        if (string.IsNullOrWhiteSpace(rawType))
        {
            return "TEXT";
        }

        var normalized = rawType.Trim().ToUpperInvariant();

        if (normalized.StartsWith("TINYINT"))
        {
            return "TINYINT";
        }
        if (normalized.StartsWith("SMALLINT"))
        {
            return "SMALLINT";
        }
        if (normalized.StartsWith("BIGINT"))
        {
            return "BIGINT";
        }
        if (normalized.StartsWith("INT"))
        {
            return "INT";
        }
        if (normalized.StartsWith("BOOLEAN"))
        {
            return "TINYINT(1)";
        }
        if (normalized.StartsWith("REAL") || normalized.StartsWith("DOUBLE") || normalized.StartsWith("FLOAT"))
        {
            return "DOUBLE";
        }
        if (DecimalPattern.IsMatch(normalized))
        {
            return DecimalPattern.Match(normalized).Value.ToUpperInvariant();
        }
        if (normalized.StartsWith("NUMERIC") || normalized.StartsWith("DECIMAL"))
        {
            return "DECIMAL(38,10)";
        }
        if (VarcharPattern.IsMatch(normalized))
        {
            var match = VarcharPattern.Match(normalized).Value.ToUpperInvariant();
            return match.Replace("CHAR", "VARCHAR");
        }
        if (normalized.Contains("CHAR"))
        {
            return "VARCHAR(255)";
        }
        if (normalized.Contains("CLOB") || normalized.Contains("TEXT"))
        {
            return "TEXT";
        }
        if (normalized.Contains("BLOB"))
        {
            return "BLOB";
        }
        if (normalized.StartsWith("DATETIME") || normalized.StartsWith("TIMESTAMP"))
        {
            return "DATETIME";
        }
        if (normalized.StartsWith("DATE"))
        {
            return "DATE";
        }
        return "TEXT";
    }

    private static string FormatDefaultValue(string defaultValue)
    {
        var cleaned = defaultValue.Trim();
        var lower = cleaned.ToLowerInvariant();

        if (lower == "null")
        {
            return "NULL";
        }

        if (Regex.IsMatch(lower, @"^datetime\s*\(\s*'now'\s*\)$") ||
            Regex.IsMatch(lower, @"^datetime\s*\(\s*'now'\s*,\s*'localtime'\s*\)$") ||
            Regex.IsMatch(lower, @"^datetime\s*\(\s*'now'\s*,\s*'utc'\s*\)$") ||
            Regex.IsMatch(lower, @"^current_timestamp\s*\(\s*\)\s*$") ||
            Regex.IsMatch(lower, @"^current_timestamp$") ||
            Regex.IsMatch(lower, @"^strftime\s*\(\s*'%Y-%m-%d %H:%M:%S'\s*,\s*'now'\s*\)$"))
        {
            return "CURRENT_TIMESTAMP";
        }

        if (Regex.IsMatch(lower, @"^date\s*\(\s*'now'\s*\)$") ||
            Regex.IsMatch(lower, @"^current_date$") ||
            Regex.IsMatch(lower, @"^current_date\s*\(\s*\)\s*$"))
        {
            return "CURRENT_DATE";
        }

        if (Regex.IsMatch(lower, @"^time\s*\(\s*'now'\s*\)$") ||
            Regex.IsMatch(lower, @"^current_time$") ||
            Regex.IsMatch(lower, @"^current_time\s*\(\s*\)\s*$"))
        {
            return "CURRENT_TIME";
        }

        return cleaned;
    }

    private static bool IsDatetimeDefault(string? defaultValue)
    {
        if (string.IsNullOrWhiteSpace(defaultValue))
        {
            return false;
        }
        var lower = defaultValue.Trim().ToLowerInvariant();
        return Regex.IsMatch(lower, @"^datetime\s*\(\s*'now'\s*\)$") ||
               Regex.IsMatch(lower, @"^datetime\s*\(\s*'now'\s*,\s*'localtime'\s*\)$") ||
               Regex.IsMatch(lower, @"^datetime\s*\(\s*'now'\s*,\s*'utc'\s*\)$") ||
               Regex.IsMatch(lower, @"^current_timestamp\s*\(\s*\)\s*$") ||
               Regex.IsMatch(lower, @"^current_timestamp$") ||
               Regex.IsMatch(lower, @"^strftime\s*\(\s*'%y-%m-%d %h:%m:%s'\s*,\s*'now'\s*\)$") ||
               Regex.IsMatch(lower, @"^strftime\s*\(\s*'%y-%m-%d %h:%m:%s'\s*,\s*'now'\s*,\s*'localtime'\s*\)$");
    }

    private static bool IsDateDefault(string? defaultValue)
    {
        if (string.IsNullOrWhiteSpace(defaultValue))
        {
            return false;
        }
        var lower = defaultValue.Trim().ToLowerInvariant();
        return Regex.IsMatch(lower, @"^date\s*\(\s*'now'\s*\)$") ||
               Regex.IsMatch(lower, @"^current_date$") ||
               Regex.IsMatch(lower, @"^current_date\s*\(\s*\)\s*$");
    }

    private static bool IsTimeDefault(string? defaultValue)
    {
        if (string.IsNullOrWhiteSpace(defaultValue))
        {
            return false;
        }
        var lower = defaultValue.Trim().ToLowerInvariant();
        return Regex.IsMatch(lower, @"^time\s*\(\s*'now'\s*\)$") ||
               Regex.IsMatch(lower, @"^current_time$") ||
               Regex.IsMatch(lower, @"^current_time\s*\(\s*\)\s*$");
    }

    private static bool IsIntegerType(string? rawType)
        => !string.IsNullOrWhiteSpace(rawType) && rawType.Contains("INT", StringComparison.OrdinalIgnoreCase);

    private static string EscapeValue(object? value)
    {
        if (value is null || value is DBNull)
        {
            return "NULL";
        }

        return value switch
        {
            bool b => b ? "1" : "0",
            byte[] bytes => $"X'{Convert.ToHexString(bytes)}'",
            sbyte or byte or short or ushort or int or uint or long or ulong => Convert.ToString(value, CultureInfo.InvariantCulture) ?? "0",
            float or double or decimal => Convert.ToString(value, CultureInfo.InvariantCulture) ?? "0",
            DateTime dt => $"'{dt:yyyy-MM-dd HH:mm:ss}'",
            _ => QuoteString(value.ToString() ?? string.Empty)
        };
    }

    private static string QuoteString(string text)
    {
        var escaped = text.Replace("\\", "\\\\").Replace("'", "\\'").Replace("\0", string.Empty);
        return $"'{escaped}'";
    }

    private static long DumpTableData(SqliteConnection connection, string tableName, int batchSize, HashSet<string> nullablePk, IReadOnlyDictionary<string, string> nullablePkValueKind, TextWriter writer)
    {
        using var cmd = connection.CreateCommand();
        cmd.CommandText = $"SELECT * FROM {QuoteIdentifier(tableName)}";
        using var reader = cmd.ExecuteReader();

        var columns = new List<string>();
        for (int i = 0; i < reader.FieldCount; i++)
        {
            columns.Add(reader.GetName(i));
        }
        if (columns.Count == 0)
        {
            return 0;
        }

        var colList = string.Join(", ", columns.Select(QuoteIdentifier));
        var colIndex = columns
            .Select((name, idx) => new { name, idx })
            .ToDictionary(x => x.name, x => x.idx, StringComparer.OrdinalIgnoreCase);

        var batch = new List<object?[]>(batchSize);
        long rowCount = 0;
        int nullPkCounter = 1;

        void Flush()
        {
            if (batch.Count == 0)
            {
                return;
            }

            var sb = new StringBuilder();
            sb.Append($"INSERT INTO {QuoteIdentifier(tableName)} ({colList}) VALUES\n  ");
            for (int i = 0; i < batch.Count; i++)
            {
                if (i > 0)
                {
                    sb.Append(",\n  ");
                }
                var row = batch[i];
                var values = row.Select(EscapeValue);
                sb.Append('(').Append(string.Join(", ", values)).Append(')');
            }
            sb.Append(";\n");
            writer.Write(sb.ToString());
            batch.Clear();
        }

        while (reader.Read())
        {
            var values = new object?[reader.FieldCount];
            reader.GetValues(values);

            int? rowPlaceholder = null;
            foreach (var col in nullablePk)
            {
                if (colIndex.TryGetValue(col, out var idx) && (values[idx] is null || values[idx] is DBNull))
                {
                    if (rowPlaceholder == null)
                        rowPlaceholder = nullPkCounter++;
                    var kind = nullablePkValueKind.TryGetValue(col, out var k) ? k : "text";
                    values[idx] = kind switch
                    {
                        "int" => -(long)rowPlaceholder.Value,
                        "real" => -(double)rowPlaceholder.Value,
                        "blob" => BitConverter.GetBytes(rowPlaceholder.Value),
                        _ => $"__null_pk_{rowPlaceholder.Value}"
                    };
                }
            }

            batch.Add(values);
            rowCount++;
            if (batch.Count >= batchSize)
            {
                Flush();
            }
        }

        Flush();
        return rowCount;
    }

    private static IEnumerable<string> DumpTableIndexes(SqliteConnection connection, string tableName)
    {
        var result = new List<string>();
        using var cmd = connection.CreateCommand();
        cmd.CommandText = $"PRAGMA index_list({QuoteIdentifier(tableName)})";
        using var reader = cmd.ExecuteReader();
        while (reader.Read())
        {
            var name = reader.GetString(1);
            var unique = reader.GetInt32(2) != 0;
            var origin = reader.GetString(3);

            if (name.StartsWith("sqlite_autoindex", StringComparison.OrdinalIgnoreCase) || origin == "pk")
            {
                continue;
            }

            using var infoCmd = connection.CreateCommand();
            infoCmd.CommandText = $"PRAGMA index_info({QuoteIdentifier(name)})";
            using var infoReader = infoCmd.ExecuteReader();
            var cols = new List<string>();
            while (infoReader.Read())
            {
                cols.Add(QuoteIdentifier(infoReader.GetString(2)));
            }

            if (cols.Count == 0)
            {
                continue;
            }

            var prefix = unique ? "CREATE UNIQUE INDEX" : "CREATE INDEX";
            result.Add($"{prefix} {QuoteIdentifier(name)} ON {QuoteIdentifier(tableName)} ({string.Join(", ", cols)});");
        }

        return result;
    }

    private static HashSet<string> IndexedColumns(SqliteConnection connection, string tableName)
    {
        var cols = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        using var cmd = connection.CreateCommand();
        cmd.CommandText = $"PRAGMA index_list({QuoteIdentifier(tableName)})";
        using var reader = cmd.ExecuteReader();
        while (reader.Read())
        {
            var name = reader.GetString(1);
            using var infoCmd = connection.CreateCommand();
            infoCmd.CommandText = $"PRAGMA index_info({QuoteIdentifier(name)})";
            using var infoReader = infoCmd.ExecuteReader();
            while (infoReader.Read())
            {
                cols.Add(infoReader.GetString(2));
            }
        }
        return cols;
    }

    private static void DumpViews(SqliteConnection connection, TextWriter writer)
    {
        using var cmd = connection.CreateCommand();
        cmd.CommandText = "SELECT name, sql FROM sqlite_master WHERE type='view' AND name NOT LIKE 'sqlite_%' ORDER BY name";
        using var reader = cmd.ExecuteReader();
        while (reader.Read())
        {
            var name = reader.GetString(0);
            var sqlText = reader.IsDBNull(1) ? null : reader.GetString(1);
            if (string.IsNullOrWhiteSpace(sqlText))
            {
                continue;
            }
            writer.WriteLine($"DROP VIEW IF EXISTS {QuoteIdentifier(name)};");
            writer.WriteLine(NormalizeSql(sqlText));
            writer.WriteLine();
        }
    }

    private static void DumpTriggers(SqliteConnection connection, TextWriter writer)
    {
        using var cmd = connection.CreateCommand();
        cmd.CommandText = "SELECT name, sql FROM sqlite_master WHERE type='trigger' AND name NOT LIKE 'sqlite_%' ORDER BY name";
        using var reader = cmd.ExecuteReader();
        while (reader.Read())
        {
            var name = reader.GetString(0);
            var sqlText = reader.IsDBNull(1) ? null : reader.GetString(1);
            if (string.IsNullOrWhiteSpace(sqlText))
            {
                continue;
            }
            writer.WriteLine($"DROP TRIGGER IF EXISTS {QuoteIdentifier(name)};");
            writer.WriteLine("DELIMITER //");
            writer.WriteLine(NormalizeSql(sqlText) + " //");
            writer.WriteLine("DELIMITER ;");
            writer.WriteLine();
        }
    }

    private static string NormalizeSql(string sql)
        => sql.Trim().TrimEnd(';') + ";";

    private sealed class TableInfo
    {
        public string Name { get; set; } = string.Empty;
        public string? Type { get; set; }
        public bool NotNull { get; set; }
        public string? DefaultValue { get; set; }
        public int PkSeq { get; set; }
    }
}
